<?php

/**
 * @file
 * Contains user_location.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_location_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_location module.
    case 'help.page.user_location':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User Site location and the current time for the location.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_location_theme() {
  return [
    'user_timezone_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
